"""Create User

Revision ID: 08797d4b4a62
Revises:
Create Date: 2025-11-19 19:27:26.764469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "08797d4b4a62"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        # UUID v7은 애플리케이션 레벨에서 생성 (uuid7 라이브러리)
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=True),
        sa.Column("profile_emoji", sa.String(length=10), nullable=True),
        sa.Column("current_points", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )

    # Partial indexes with deleted_at IS NULL condition for soft delete
    op.create_index(
        index_name="idx_users_email",
        table_name="users",
        columns=["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        index_name="idx_users_nickname",
        table_name="users",
        columns=["nickname"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # Create updated_at trigger function
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # Create trigger for users table
    op.execute("""
        CREATE TRIGGER update_users_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop trigger first (depends on table and function)
    op.execute("DROP TRIGGER IF EXISTS update_users_updated_at ON users;")

    # Drop partial indexes
    op.drop_index("idx_users_nickname", table_name="users")
    op.drop_index("idx_users_email", table_name="users")

    # Drop table
    op.drop_table("users")

    # Drop trigger function
    # 주의: 이 함수는 다른 테이블(cities, tickets 등)에서도 재사용됩니다.
    # 다른 테이블이 이미 생성된 경우, 해당 테이블들을 먼저 downgrade 해야 합니다.
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    # ### end Alembic commands ###
