"""add room_stay checkout flags and notification table

Revision ID: d37203dff9c9
Revises: b2c3d4e5f600
Create Date: 2025-12-29 11:29:49.759364

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d37203dff9c9"
down_revision: str | Sequence[str] | None = "b2c3d4e5f600"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_dm_rooms_room_users_partial"),
        table_name="direct_message_rooms",
        postgresql_where="((deleted_at IS NULL) AND ((status)::text <> ALL ((ARRAY['rejected'::character varying, 'ended'::character varying])::text[])))",
    )
    op.create_unique_constraint(
        "uq_dm_rooms_room_users", "direct_message_rooms", ["room_id", "requester_id", "receiver_id"]
    )
    op.drop_constraint(op.f("direct_messages_dm_room_id_fkey"), "direct_messages", type_="foreignkey")
    op.create_foreign_key(None, "direct_messages", "direct_message_rooms", ["dm_room_id"], ["dm_room_id"])
    op.add_column(
        "room_stays",
        sa.Column("is_checkout_reminder_sent", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_stays", "is_checkout_reminder_sent")
    op.drop_constraint(None, "direct_messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("direct_messages_dm_room_id_fkey"),
        "direct_messages",
        "direct_message_rooms",
        ["dm_room_id"],
        ["dm_room_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_dm_rooms_room_users", "direct_message_rooms", type_="unique")
    op.create_index(
        op.f("uq_dm_rooms_room_users_partial"),
        "direct_message_rooms",
        ["room_id", "requester_id", "receiver_id"],
        unique=True,
        postgresql_where="((deleted_at IS NULL) AND ((status)::text <> ALL ((ARRAY['rejected'::character varying, 'ended'::character varying])::text[])))",
    )
    # ### end Alembic commands ###
